const team = [
    {
        name: "Vedang Gotmare ",
        position: "President",
        imgurl: "vedang.jpg",
        instagram: "https://www.instagram.com/vedanggotmare/?hl=fb-ha",
        linkedin: "https://www.linkedin.com/in/vedang-gotmare-899929272/",
        phone: "+91 8767648176",
    },
    {
        name: "Sarvesh Patil",
        imgurl: "sarvesh.jpg",
        position: "Vice President",
        instagram: "https://www.instagram.com",
        linkedin: "https://www.linkedin.com",
        phone: "+91 7875501375",
    },
    {
        name: "Dhiraj Madhavaram",
        position: "Head Of Content Creation",
        imgurl: "dhiraj.png",
        instagram: "https://www.instagram.com/dhiraj___265/",
        linkedin: "https://www.linkedin.com/in/dhiraj-madhavaram-8a6057251/",
        phone: "+91 9059129965",
    },
    {
        name: "Prashita Verma",
        position: "Treasurer",
        imgurl: "prashita.jpg",
        instagram: "https://www.instagram.com",
        linkedin: "https://www.linkedin.com/in/prashita-verma-783101255",
        phone: "+91 8700370355",
    },
    {
        name: "Anjali Mali",
        position: "Head Of Public Relations",
        imgurl: "anjali.jpg",
        instagram: "https://www.instagram.com",
        linkedin: "https://www.linkedin.com",
        phone: "+91 9326657638",
    },
    {
        name: "Aditi Verma",
        position: "Head Of Design",
        imgurl: "aditi.jpg",
        instagram: "https://www.instagram.com/aditiv41?igsh=MWVkYjYwNHJqaHQzOA==",
        linkedin: "https://www.linkedin.com/in/aditi-verma-556ba2278",
        phone: "+91 9324040865",
    },
    {
        name: "Aabha Nadgouda",
        position: "Head Of Research",
        imgurl: "aabha.jpg",
        instagram: "https://www.instagram.com/aabhanadgouda",
        linkedin: "https://www.linkedin.com/in/aabha-nadgouda-9976a9295",
        phone: "+91 9137977464",
    },
    {
        name: "Anurag Ninawe",
        position: "Head Of Instrumental Research",
        imgurl: "anuragn.jpg",
        instagram: "https://www.instagram.com",
        linkedin: "http://linkedin.com",
        phone: "+91 7304681059",
    },
    {
        name: "Vardhan Sunkara",
        position: "Head of Multimedia",
        imgurl: "vardhan.jpg",
        instagram: "https://www.instagram.com/vardhansunkara/profilecard/?igsh=MW9tZnR1aGVpeDQ2eA==",
        linkedin: "https://www.linkedin.com/in/vardhan-sunkara-2b1ab2281/",
        phone: "+91 7095880006",
    },

];

export default team;
